version: 2
jobs:
  build:
    working_directory: ~/~

    docker:
      - image: circleci/openjdk

    steps:

      - checkout

      - restore_cache:
          key: -{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: -{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/

      - store_artifacts:
          path: target/cloud-1.0.jar
  deploy:

    working_directory: ~/~

    docker:
      - image: circleci/openjdk

    steps:

      - checkout

      - run:
          name: clever deploy
          command: |
            git remote add clever https://$CLEVER_TOKEN:$CLEVER_SECRET@push-par-clevercloud-customers.services.clever-cloud.com/$CLEVER_APP_ID.git
            git push --verbose clever master 2>&1 | grep -e 'remote:' -e '->'
workflows:
  version: 2
  build_and_deploy:

    jobs:
      - build

      - deploy:
          requires:
           - build
          filters:
            branches:
              only: master
